### ISSUE TITLE
Can't undo/redo in code editor

### ISSUE THREAD

**Issue by oliviertassinari** [mui/toolpad#349]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Can't undo/redo in code editor

### Expected behavior 🤔

Can

### Steps to reproduce 🕹

1. Open https://master--toolpad.mui.com/_toolpad/app/cl1c2j0l512939zo6a43575en/editor/codeComponents/cl27gnq88000a3f69zk039hf1
2. Try

**Comment by oliviertassinari** [comment]
Niiice

**Comment by oliviertassinari** [comment]
However, undo doesn't work as soon as the content is saved, expected?

**Comment by Janpot** [comment]
Yeah, the integration with monaco editor is not stellar. I tried to treat it as a controlled component, but it doesn't seem to be optimized for that. Iterating further in https://github.com/mui/mui-toolpad/pull/354
