### ISSUE TITLE
[docs] Refine Toolpad sections on Material UI docs

### ISSUE THREAD

**Issue by Janpot** [mui/toolpad#4007]
### Summary

* Don't frame it as "Experimental API" https://github.com/mui/material-ui/pull/43036#discussion_r1734572495
    Proposal: Name all these sections "Toolpad"
* Add example for notifications and dialogs https://github.com/mui/material-ui/pull/43036#discussion_r1734571033
    Proposal: Make it similar to the notistack example. Indicate well that this is not native Material UI
 - Don't call it a "framework" here: https://mui.com/material-ui/getting-started/templates/#toolpad-core-beta

**Comment by oliviertassinari** [comment]
> Proposal: Name all these sections "Toolpad"

For Dialog, Snackbar, it can make sense to me. Long-term these would be in Material UI? It's the layout component that felt strange.
