### ISSUE TITLE
[docs] Add file location on all demos and code snippets

### ISSUE THREAD

**Issue by prakhargupta1** [mui/toolpad#4020]
### Summary

I find these file locators (screenshot below) very helpful. But these seem to missing on some of the component docs and demos. 

<img width="855" alt="Screenshot 2024-08-30 at 12 15 55 PM" src="https://github.com/user-attachments/assets/f1c93a4f-f699-4e25-a9d6-689491cf7b42">

### Motivation

Better DX

**Search keywords**: file

**Comment by Janpot** [comment]
Can you list which demos exactly you think should have these? And which filename they should have.
Most of the component demos are runtime agnostic, so the filename is irrelevant.
