### ISSUE TITLE
Search bar looks strange when filled on dark mode

### ISSUE THREAD

**Issue by Janpot** [mui/toolpad#4037]
### Steps to reproduce

1. Visit https://deploy-preview-3984--mui-toolpad-docs.netlify.app/toolpad/core/react-dashboard-layout/#customization
2. put something in the search bar

### Current behavior

It looks a bit off ![Screenshot 2024-09-03 at 14 35 15](https://github.com/user-attachments/assets/faf1fae2-9cd2-4b97-9013-554074a5a9cc)

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: search bar

**Comment by apedroferreira** [comment]
Looks fine for me... you just typed anything in the search bar with the demo in dark mode?

**Comment by apedroferreira** [comment]
I've tried but so far couldn't find a way to get autofill suggestions on that demo on Chrome.
LMK if there's a way or if you can debug this better.
Also not sure if this isn't normal behavior or a possible issue with the MUI Core component...

**Comment by Janpot** [comment]
There's https://github.com/mui/material-ui/issues/33519, but you could probably just remove the `id="search"` from the input
