### ISSUE TITLE
[template] [ux] `SignInPage` improvements

### ISSUE THREAD

**Issue by bharatkashyap** [mui/toolpad#4067]
| Current | Proposed |
| ------- | -------- |
| <img width="400" alt="Screenshot 2024-09-10 at 2 03 30 PM" src="https://github.com/user-attachments/assets/48cd518e-d167-4a37-a615-0bb25d929ecd"> |  <img src="https://github.com/user-attachments/assets/79a5dc07-441a-4add-a799-f0582f6fbf0f" width=400> |

- @zanivan We are also in the process of adding [passkey](https://deploy-preview-4063--mui-toolpad-docs.netlify.app/toolpad/core/react-sign-in-page/#passkey) and magic links options, perhaps the reordering would need to consider the placement of these options as well?

- Figma: https://www.figma.com/design/14OEUnwh4ahMb2empYAEc8/Toolpad-UX?node-id=1538-175100&node-type=frame&t=mx15fYGux742bCAt-0

**Search keywords**:

**Comment by zanivan** [comment]
[Done](https://www.figma.com/design/14OEUnwh4ahMb2empYAEc8/Toolpad-UX?node-id=1538-175100&t=t53KMxuo9XMkBJ9g-4)!

![image](https://github.com/user-attachments/assets/85d1e651-9583-44b7-85a1-16728666f408)

**Comment by bharatkashyap** [comment]
> [Done](https://www.figma.com/design/14OEUnwh4ahMb2empYAEc8/Toolpad-UX?node-id=1538-175100&t=t53KMxuo9XMkBJ9g-4)!

Appreciate the speed 😄  There is a little complexity though, the Passkey provider requires a text field as well, which is why I was wondering what the ideal UI would be for its placement within this list

**Comment by aress31** [comment]
Adding a theme switcher would also be beneficial; then it would feel complete.
