### ISSUE TITLE
PageContainer's title and breadcrumbs don't take the navigation segment into account

### ISSUE THREAD

**Issue by bourquep** [mui/toolpad#4100]
### Steps to reproduce

Using the newly introduced `segment` property in `AppProvider` navigation. It does work in terms of selecting the proper navbar item when the current URL matches the segment, but the `PageContainer` doesn't seem to be able to properly extract/display the page title and breadcrumbs:

<img width="282" alt="image" src="https://github.com/user-attachments/assets/f585ce6b-de5e-45be-9f59-e5177a46024b">

<img width="674" alt="image" src="https://github.com/user-attachments/assets/2cc5eb0a-c8e6-4f9a-b030-39bd637de81f">

<img width="729" alt="image" src="https://github.com/user-attachments/assets/69932ccd-8f97-4b3f-85f8-3bb96105c3ae">

### Current behavior

The `AppProvider.title` is displayed for both breadcrumbs and title by `PageContainer`.

### Expected behavior

Breadcrumbs should be `Studyo Go Admin / Users / 1234` and title should be settable via `PageProvider.title`.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 14.6.1
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 128.0.6613.138
    Edge: Not Found
    Safari: 17.6
  npmPackages:
    @emotion/react: 11.13.3 => 11.13.3
    @emotion/styled: 11.13.0 => 11.13.0
    @mui/base:  5.0.0-beta.58
    @mui/core-downloads-tracker:  6.1.0
    @mui/icons-material: 6.1.0 => 6.1.0
    @mui/lab:  6.0.0-beta.9
    @mui/material: 6.1.0 => 6.1.0
    @mui/private-theming:  6.1.0
    @mui/styled-engine:  6.1.0
    @mui/system:  6.1.0
    @mui/types:  7.2.16
    @mui/utils:  6.1.0
    @toolpad/core: 0.6.0 => 0.6.0
    @toolpad/utils:  0.6.0
    @types/react: ^18 => 18.3.5
    react: ^18 => 18.3.1
    react-dom: ^18 => 18.3.1
    typescript: ^5 => 5.5.4
```
</details>

**Search keywords**: segment

**Comment by Janpot** [comment]
@bourquep How would you feel about if we added a `title` and `breadcrumbs` property to the `PageContainer` to allow you to override for specific instances? It would still fall bac to the current behavior.

**Comment by bourquep** [comment]
That would be great!
