### ISSUE TITLE
[docs] Feedback on Naming Convention | breadCrumbs

### ISSUE THREAD

**Issue by douglaszaltron** [mui/toolpad#4128]
### Related page

https://mui.com/toolpad/core/react-page-container/#title-and-breadcrumbs

### Kind of issue

Unclear explanations

### Issue description

I found the use of PascalCase for the name "Breadcrumbs" to be odd. The props are named "breadCrumbs," which I think doesn’t look good. It would be better to use "breadcrumbs" since it's a single word and isn’t meant to be read separately.

### Context

Docs

**Search keywords**: breadcrumbs

**Comment by Janpot** [comment]
You are right, [Material UI](https://mui.com/material-ui/react-breadcrumbs/) also uses "breadcrumbs". Will update.
