### ISSUE TITLE
Can't start dev from starter app using pnpm

### ISSUE THREAD

**Issue by pencilcheck** [mui/toolpad#4144]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Follow the steps and create a starter app from the website
2. Run pnpm dev
3. Error

```
╰─λ pnpm toolpad-studio:dev                                                                                                                                0 (8.904s)

> my-toolpad-studio-app@0.1.0 toolpad-studio:dev /Users/user/Projects/my-toolpad-studio-app
> toolpad-studio dev ./my-toolpad-app

info  - starting Toolpad Studio application in dev mode...
(node:16357) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
info  - Initializing .gitignore file
info  - loaded env file "/Users/user/Projects/my-toolpad-studio-app/.env" with keys DATABASE_URL
ready - Toolpad Studio project /Users/user/Projects/my-toolpad-studio-app/my-toolpad-app ready on http://localhost:3000/
App dev server failed 1
 ELIFECYCLE  Command failed with exit code 1
```

### Current behavior

```
╰─λ pnpm toolpad-studio:dev                                                                                                                                0 (8.904s)

> my-toolpad-studio-app@0.1.0 toolpad-studio:dev /Users/user/Projects/my-toolpad-studio-app
> toolpad-studio dev ./my-toolpad-app

info  - starting Toolpad Studio application in dev mode...
(node:16357) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
info  - Initializing .gitignore file
info  - loaded env file "/Users/user/Projects/my-toolpad-studio-app/.env" with keys DATABASE_URL
ready - Toolpad Studio project /Users/user/Projects/my-toolpad-studio-app/my-toolpad-app ready on http://localhost:3000/
App dev server failed 1
 ELIFECYCLE  Command failed with exit code 1
```

### Expected behavior

To start website on localhost:3000

### Context

Just trying out the example, only tried pnpm and npm, and pnpm doesn't work.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>
Need to install the following packages:
@mui/envinfo@2.0.26
Ok to proceed? (y)

  System:
    OS: macOS 14.4.1
  Binaries:
    Node: 22.7.0 - /opt/homebrew/bin/node
    npm: 10.8.2 - /opt/homebrew/bin/npm
    pnpm: 8.2.0 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 124.0.6367.80
    Edge: 120.0.2210.61
    Safari: 17.4.1
  npmPackages:
    @toolpad/studio: ^0.7.0 => 0.7.0
    @types/react: ^18.3.3 => 18.3.3
    react: ^18.3.1 => 18.3.1
    react-dom: ^18.3.1 => 18.3.1
    typescript: ^5.5.3 => 5.5.3

**Search keywords**: App dev server failed 1

**Comment by Janpot** [comment]
I ran
* `pnpm create toolpad-app --studio my-toolpad-app`
* `cd my-toolpad-app`
* `pnpm dev`
This is my output
```
> toolpad-studio dev

info  - starting Toolpad Studio application in dev mode...
info  - Initializing .gitignore file
info  - loaded env file "/Users/janpotoms/Desktop/my-toolpad-app/.env" with keys 
ready - Toolpad Studio project /Users/janpotoms/Desktop/my-toolpad-app/toolpad ready on http://localhost:3000/
ready - built functions.ts: 0 error(s), 0 warning(s)
```

I can open the app in the browser and drag and drop components.

In order to help you further with this issue, please provide a full reproduction under the form of a github repository, or a zip file.

**Comment by pencilcheck** [comment]
> I ran
> 
> * `pnpm create toolpad-app --studio my-toolpad-app`
> * `cd my-toolpad-app`
> * `pnpm dev`
>   This is my output
> 
> ```
> > toolpad-studio dev
> 
> info  - starting Toolpad Studio application in dev mode...
> info  - Initializing .gitignore file
> info  - loaded env file "/Users/janpotoms/Desktop/my-toolpad-app/.env" with keys 
> ready - Toolpad Studio project /Users/janpotoms/Desktop/my-toolpad-app/toolpad ready on http://localhost:3000/
> ready - built functions.ts: 0 error(s), 0 warning(s)
> ```
> 
> I can open the app in the browser and drag and drop components.
> 
> In order to help you further with this issue, please provide a full reproduction under the form of a github repository, or a zip file.

It is literally
`pnpm create toolpad-app --studio my-toolpad-app`

I don't know what else to give you, it is the default app from toolpad-app creator
