### ISSUE TITLE
[template] Support Account component on the bottom left 

### ISSUE THREAD

**Issue by bharatkashyap** [mui/toolpad#4147]
I would assume, that the developer would also to remove the header bar and have everything in the sidenav?
Example: https://dashboard.tremor.so/overview

Idea: add a variant to the account component that has avatar + username/email. To be used in the dashboard footer slot

- [x] https://github.com/mui/toolpad/issues/4102
- [x] https://github.com/mui/mui-toolpad/issues/4101

**Search keywords**:

**Comment by douglaszaltron** [comment]
https://dashboard.tremor.so/overview nice ✨
