### ISSUE TITLE
Documentation/Example for Vite and ReactRouter

### ISSUE THREAD

**Issue by nikolayg** [mui/toolpad#4149]
### Summary

The [toolpad website](https://mui.com/toolpad/) mentions it supports Vite, but all examples use Next. Also, the `create-toolpad-app` tool only support Next. I couldn't find any examples of using plain Vite and ReactRouter (or another routing library).

Is the integration with Vite mature and where can I find examples?

**Search keywords**: Vite ReactRouter

**Comment by apedroferreira** [comment]
TODO: 
- Add example with React Router
- Support Vite starter in `create-toolpad-app`
- Add Vite project playground for development

**Comment by apedroferreira** [comment]
Support for a Vite starter in `create-toolpad-app` will be worked on as a separate issue and planned for v0.9.0: https://github.com/mui/toolpad/issues/4235

React Router integration guide and Vite examples will be added in https://github.com/mui/toolpad/pull/4185, planned for v0.8.0.
