### ISSUE TITLE
[core] Optimize Theme Mode Selector in Header

### ISSUE THREAD

**Issue by douglaszaltron** [mui/toolpad#4151]
### Summary

When we have the ability in the theme to select mode (system, dark, and light), a toggle button is created in the header. However, this element occupies precious space in the header that could be used for other types of configurations. The proposal is to follow the MUI documentation style, where there is a gear button that contains configuration options, including the mode selector, along with other settings.

For example: language preferences, display preferences, among others.

### Examples

<img width="323" alt="Captura de Tela 2024-09-24 às 10 48 13" src="https://github.com/user-attachments/assets/7e0efbc5-1bd9-47bf-8ae2-6e29e9589ad6">
<img width="418" alt="Captura de Tela 2024-09-24 às 10 48 17" src="https://github.com/user-attachments/assets/c032b48a-c92e-42dc-a820-c670080e8005">

**Search keywords**: theme

**Comment by Janpot** [comment]
Assuming there are going to be many different ways of how users would want this to be executed, perhaps step 1 should be to create the minimum API necessary to customize this in user land.
It's already possible to build your own theme toggle with the [`useColorScheme`](https://mui.com/system/experimental-api/css-theme-variables/#usecolorscheme-colorschemecontextvalue) hook. The one thing missing then is a way to hide the theme toggle in the header. 

cc @apedroferreira Perhaps a quick win here could be to add a slot for the theme toggle

**Comment by apedroferreira** [comment]
> Assuming there are going to be many different ways of how users would want this to be executed (*), perhaps step 1 should be to create the minimum API necessary to customize this in user land. It's already possible to build your own theme toggle with the [`useColorScheme`](https://mui.com/system/experimental-api/css-theme-variables/#usecolorscheme-colorschemecontextvalue) hook. The one thing missing then is a way to hide the theme toggle in the header.
> 
> cc @apedroferreira Perhaps a quick win here could be to add a slot for the theme toggle?
> 
> (*) I'm imagining
> 
> * a toggle button
> * a drawer as per this issue
> * a button with popover
> * on a separate settings page
> * no toggle at all, just follow the system preference
> * ...

Sounds good, we have 2 slots in the header right now (account + additional actions), but the theme is outside of them.
I guess we should have the minimum amount of slots in the header than can be completely overriden.

**Comment by ebengtso** [comment]
Hi, I would like to restore the user theme's choice when user logins back. Is it possible to provide a Slotprops for Theme's user action?
Thanks

**Comment by Janpot** [comment]
@ebengtso Can you elaborate a bit more on what you're trying to do?

Are you storing the dark/light mode choice in the user record on the backend? You should be able to already achieve that functionality with `mode` and `setMode` returned by the [`useColorScheme`](https://mui.com/system/experimental-api/css-theme-variables/#usecolorscheme-colorschemecontextvalue) hook.

**Comment by ebengtso** [comment]
> @ebengtso Can you elaborate a bit more on what you're trying to do?
> 
> Are you storing the dark/light mode choice in the user record on the backend? You should be able to already achieve that functionality with `mode` and `setMode` returned by the [`useColorScheme`](https://mui.com/system/experimental-api/css-theme-variables/#usecolorscheme-colorschemecontextvalue) hook.

Thanks. Two distinct issues: 

1) I had a wrapping ThemeProvider. I removed it and it worked. It was disturbing the following AppProvider.

2)  In the below I was expecting debug to print, but it's not printing when I switch the theme.

const {mode, setMode} = useColorScheme();

  useEffect(() => {
console.debug(mode)
  }, [mode]);

**Comment by Janpot** [comment]
Regarding 2. The following works for me https://codesandbox.io/embed/gcnmgl?module=/src/Demo.tsx

**Comment by Janpot** [comment]
@ebengtso Here's a [stackblitz](https://stackblitz.com/edit/react-xcgdx3?file=Demo.tsx) that demonstrates `useColorScheme`. Make sure to call it in a component that's rendered under the `DashboardLayout`.

**Comment by douglaszaltron** [comment]
In this case, where the hook is exported, the dashboard could have the option of a slot for the theme. This way, we could set it to null and customize it through the action or account slot.
