### ISSUE TITLE
React does not recognize the `breadCrumbs` prop on a DOM element. PageContainer

### ISSUE THREAD

**Issue by alfi-dim** [mui/toolpad#4184]
### Steps to reproduce

Link to live example: ([required](https://dplzjp-3000.csb.app/))

Steps:
1. Create custom content wrapper using PageContainer
2. Adding "breadcrumbs" on PageContainer as "breadcrumbs" props is not work, but it works when adding as "breadCrumbs" props but got warning

### Current behavior

![Image](https://github.com/user-attachments/assets/3a716e25-fa72-468e-bc51-8372efb6e937)

### Expected behavior

it should not give warning when adding breadCrumbs props, or if it really using breadcrumbs is the right way, it should render the breadcrumbs

### Context

the code

```js
export default function ContentWrapper({ pageProps, centered, children }) {
  const { title, breadcrumbs } = pageProps;

  const classNames= `flex flex-col ${centered ? 'items-center' : ''} gap-2 border-t pt-2 border-t-gray-400`
  return (
    <PageContainer
      title={title}
      breadCrumbs={breadcrumbs}
    >
      <section className={classNames}>
        {children}
      </section>
    </PageContainer>
  )
}
```

page when add breadCrumbs props
![Image](https://github.com/user-attachments/assets/ff96e172-a2c0-440b-83b4-391b9a96eea4)

page when add breadcrumbs props
![Image](https://github.com/user-attachments/assets/776c68dc-7dd7-4eed-8aa9-4e489f71f967)

in case you wonder what that error box on nextjs looks like
![Image](https://github.com/user-attachments/assets/285f6f43-79c8-4b15-aeb8-289a48abb41d)
![Image](https://github.com/user-attachments/assets/860e5e34-a41f-49a6-9cdd-8b399829db56)

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
    System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 18.20.4 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Chromium (129.0.2792.52) (MS Edge Version 129.0.2792.65 (Official build) (64-bit))
  npmPackages:
    @emotion/react:  11.13.3
    @emotion/styled: ^11.13.0 => 11.13.0
    @mui/base:  5.0.0-beta.58
    @mui/core-downloads-tracker:  6.1.1
    @mui/icons-material: ^6.1.1 => 6.1.1
    @mui/lab: ^6.0.0-beta.10 => 6.0.0-beta.10
    @mui/material: ^6.1.1 => 6.1.1
    @mui/material-nextjs: ^6.1.1 => 6.1.1
    @mui/private-theming:  6.1.1
    @mui/styled-engine:  6.1.1
    @mui/system:  6.1.1
    @mui/types:  7.2.17
    @mui/utils:  6.1.1
    @mui/x-data-grid: ^7.18.0 => 7.18.0
    @mui/x-internals:  7.18.0
    @toolpad/core: ^0.7.0 => 0.7.0
    @toolpad/utils:  0.7.0
    @types/react:  18.3.10
    react: ^18 => 18.3.1
    react-dom: ^18 => 18.3.1
    typescript:  5.6.2

```
</details>

**Search keywords**: pagecontainer

**Comment by Janpot** [comment]
@alfi-dim That reproduction links to a preview, can you share the actual codesandbox so that I can inspect the code?

**Comment by alfi-dim** [comment]
Alright thanks, I'll update to you later to see if the  issue is still persist.

Have a nice day.
