### ISSUE TITLE
useActivePage using outdated pattern definition

### ISSUE THREAD

**Issue by xinmingzh** [mui/toolpad#4186]
### Steps to reproduce

useActivePage expects pattern to start with leading slash `/`, but pattern definition is updated to be without leading slash.

**Search keywords**: core

**Comment by Janpot** [comment]
@xinmingzh Can you provide a codesandbox that demonstrates the problem?

**Comment by xinmingzh** [comment]
https://codesandbox.io/p/sandbox/currying-leaf-pdcksp

Orders nav should be active, but is not active.

**Comment by Janpot** [comment]
Thank you, fixing it in https://github.com/mui/toolpad/pull/4191
