### ISSUE TITLE
Allow hiding the navigation bar and toggle button

### ISSUE THREAD

**Issue by vikasgurjar** [mui/toolpad#4229]
### Summary

Allow hiding the navigation bar and toggle button in case we just want to show the header

### Motivation

In my app I want to use toolpad to handle navigation and header after a user logs in. But I have a case where user needs to wait before they are verified to see other pages, and on that page I just need the header.

I guess I can use the AppBar component from MUI but that would require me to handle `account` flow separately. 

**Search keywords**: hide navigation

**Comment by Janpot** [comment]
We could approach this in tow different ways:

1. Support a `hideNavigation: boolean` prop to hide the navigation surface
2. Provide slots for each top-level surface (navigation, appBar) so that you can replace it with an empty component

**Comment by vikasgurjar** [comment]
> 1. Support a `hideNavigation: boolean` prop to hide the navigation surface

This should be straight forward. I can work on this and raise a PR too. I wanted to know other than the changes in the core package, test cases and docs update for the new prop, is there a need for example too?

**Comment by bharatkashyap** [comment]
> 2. Provide slots for each top-level surface (navigation, appBar) so that you can replace it with an empty component

This makes sense to me from a long-term reusability perspective - separating the drawer and appBar into separate slots which can be overriden

**Comment by apedroferreira** [comment]
> any other ideas?

We've talked about separating the components that make up the layout and exporting them, including the header and the sidebar. I guess that might also work?

**Comment by vikasgurjar** [comment]
@apedroferreira can you point me the files where I need to add the documentation and demo?

**Comment by apedroferreira** [comment]
On second thought the prop makes most sense for now as it can be used to hide the menu icon too besides the sidebar itself, which the other options wouldn't be able to do so elegantly.
