### ISSUE TITLE
[core] Allow changing the width of the drawer in dashboard layout component

### ISSUE THREAD

**Issue by prakhargupta1** [mui/toolpad#4266]
### Summary

User request: https://discord.com/channels/1131323012554174485/1295843734969122866

**Search keywords**: drawer

**Comment by Janpot** [comment]
Should we support resizing as well? Could be a pro feature even.

**Comment by apedroferreira** [comment]
> Should we support resizing as well? Could be a pro feature even.

We could, but not sure if anyone would really want to be able to resize?

About this feature, I guess we can allow it through the `sx` prop if possible, or provide a specific prop to set a width, I'll give it a try to decide what's best.

**Comment by garryxiao** [comment]
I checked the code, add a new property like 'drawerWidth' to DashboardLayoutProps would help.
`drawerWidth?: number | ((isMini: boolean) => number)`
`const drawerWidth = typeof drawerWidth === 'function' ? drawerWidth(isMini) : isMini ? 64 : drawerWidth ?? 320;`

**Comment by apedroferreira** [comment]
> I checked the code, add a new property like 'drawerWidth' to DashboardLayoutProps would help. `drawerWidth?: number | ((isMini: boolean) => number)` `const drawerWidth = typeof drawerWidth === 'function' ? drawerWidth(isMini) : isMini ? 64 : drawerWidth ?? 320;`

Something like that sounds like probably the best approach!
Feel free to open a PR with something like a `sidebarExpandedWidth` prop that simply takes a number in pixels, or I can get to it eventually :)
I think we can keep the mini variant width at a constant 64px to keep it simple for now (no function needed).

**Comment by garryxiao** [comment]
Yes I agree. The mini variant width is not only for the icons, also decide the top left width. I leared to make the changes. Any issues please fix for me. Thanks.
PR: https://github.com/mui/toolpad/pull/4296
