### ISSUE TITLE
More controls for the theme switcher

### ISSUE THREAD

**Issue by garryxiao** [mui/toolpad#4291]
### Summary

Currently, the only way to hide the switcher I found is to disable the 'light' or 'dark' mode.
`
const demoTheme = extendTheme({
  colorSchemes: { light: true, dark: false },
  colorSchemeSelector: "class",
  breakpoints: {
    values: {
      xs: 0,
      sm: 600,
      md: 600,
      lg: 1200,
      xl: 1536
    }
  }
});
`
More than that, it should support to hide it by a more straightforward way, and also provide the possiblility to create the icon in some other places, not only a static existing icon there.

**Search keywords**: switcher

**Comment by bharatkashyap** [comment]
Similar to #4151 - the proposal is to 

1. Showcase the `useColorScheme` hook in a demo so users know how to build their own theme switcher
2. Add a slot for the theme switcher in the `DashboardLayout` so users can hide it 

@apedroferreira

**Comment by aress31** [comment]
@apedroferreira would be good to be able to just pass `slotProps` to override the theme switcher to for example change the color to inherit rather than primary.

**Comment by apedroferreira** [comment]
Closed by https://github.com/mui/toolpad/pull/4340

> @apedroferreira would be good to be able to just pass `slotProps` to override the theme switcher to for example change the color to `inherit` rather than `primary`.

The ThemeSwitcher is going to be in the `toolbarActions` slot from now on.
To change that color, maybe you can use the `sx` prop in `DashboardLayout` and target the icon buttons in the header/AppBar?

**Comment by aress31** [comment]
@apedroferreira Just a thought — it might be more intuitive to have a slotProps property on the DashboardLayout, similar to how it's implemented in the DataGrid. This would allow us to pass properties directly to subcomponents. For instance:

```js
<DashboardLayout 
  slotProps={{ themeSwitcher: { sx: { color: 'inherit' } } }} 
/>
```

What do you think?

**Comment by apedroferreira** [comment]
> @apedroferreira Just a thought — it might be more intuitive to have a slotProps property on the DashboardLayout, similar to how it's implemented in the DataGrid. This would allow us to pass properties directly to subcomponents. For instance:
> 
> ```js
> <DashboardLayout 
>   slotProps={{ themeSwitcher: { sx: { color: 'inherit' } } }} 
> />
> ```
> 
> What do you think?

Yes, good idea, we could probably create a nested slot for the default theme switcher, will consider it!
