### ISSUE TITLE
Allow PageContainer Children to Fully Utilize Viewport Height

### ISSUE THREAD

**Issue by aress31** [mui/toolpad#4324]
### Summary

It appears that the children of a PageContainer cannot fully utilize the entire height of the visible viewport (i.e., 100% height). It would be beneficial to either add a prop or redesign the component to enable this functionality. If achieving this with the sx prop is already possible, please let me know, and consider documenting this feature.

### Examples

```js
    <DashboardLayout defaultSidebarCollapsed>
      <PageContainer
        slots={{ toolbar: PageToolbar }}
        fixed
        disableGutters
        sx={{ minWidth: "100%", bgcolor: "cyan" }}
      >
        <Box
          sx={{
            bgcolor: "purple",
            height: "100%",
          }}
        >
          Test
        </Box>
      </PageContainer>
    </DashboardLayout>
```

### Motivation

This design is commonly found in web applications.

**Search keywords**: full height

**Comment by Janpot** [comment]
PageContainer should behave as a Container component, but with a header. I believe the original Container could be made to behave this way with an `sx` prop?

Are you interested in contributing a fix?

**Comment by apedroferreira** [comment]
Yes, this is possible to do directly inside the `DashboardLayout` as shown in https://mui.com/toolpad/core/react-dashboard-layout/#full-size-content, but does not seem to work yet inside the `PageContainer` component.

Making it so that the `Container` that wraps the whole `PageContainer` component in https://github.com/mui/toolpad/blob/master/packages/toolpad-core/src/PageContainer/PageContainer.tsx has `sx={{ flex: 1 }}` should be a good fix?

Feel free to create a PR, or we can create one later.

**Comment by SamuelLeapifai** [comment]
I would also like to vote for this feature. I looked into the source code - the PageContainer renders child Stacks, divs and a parent Container, so even if we modify the PageContainer with sx, this is not passed down to those children. Those child divs won't inherit height 100%, so my own component's height 100% is ignored. It would be great to either add this as a prop to PageContainer or have a separate FullHeightPageContainer component with min-height set to 100% or 100vh etc.

**Comment by Janpot** [comment]
I think where we potentially could go with this is to extract a PageHeader component out of what is now PageContainer and let users wrap it themselves (or not) with a Material UI Container. Then deprecate that PageContainer altogether.

Would that make sense?

**Comment by aress31** [comment]
@Janpot that would still introduce an issue of having to calculate the Page Header height and subtract it to 100vh to achieve a full height layout.

**Comment by SamuelLeapifai** [comment]
> I think where we potentially could go with this is to extract a PageHeader component out of what is now PageContainer and let users wrap it themselves (or not) with a Material UI Container. Then deprecate that PageContainer altogether.
> 
> Would that make sense?

Or keep it and just export the PageHeader. I think PageContainer "as is" is great and simple. Has nice defaults. It's just not overridable enough - in that case would be better to pick and choose only what we need (the whole header with title and breadcrumbs, in our case). We have around 10 pages so far, and only 3 pages are "full screen". The rest is using PageContainer as is and we like it.

**Comment by SamuelLeapifai** [comment]
> @Janpot that would still introduce an issue of having to calculate the `PageHeader` height and subtract it to `100vh` to achieve a full height layout.

would it? You should still be able to write your own container, give it 100% height, and put header with one more div into it (this div also has 100% height), no?
