### ISSUE TITLE
Navigation Makes More Sense on as a DashboardLayout prop

### ISSUE THREAD

**Issue by aress31** [mui/toolpad#4327]
### Summary

Applying the `navigation` prop directly to the `DashboardLayout`  component is logical, as it governs the drawer items and navigation. This approach enables the creation of multiple `DashboardLayouts`, each with its unique set of navigation items.

### Motivation

Separating the `AppProvider` from the `DashboardLayout` in terms of navigation.

**Search keywords**: navigation

**Comment by apedroferreira** [comment]
> > Navigation Makes More Sense on as a DashboardLayout prop
> 
> counter argument: both dashboard layout and page header components need to look at the same navigation structure to provide a coherent experience between them. Your use case of multiple layouts rendered together seems a very theoretical one to me. do you have any real world use cases for this?

I forgot to consider that...
So if the provided use cases really justify this change, maybe it's another problem we should solve, for example by making it possible for `PageContainer` to receive its own navigation (maybe sounds a bit awkward), or reading from a subcontext set by `DashboardLayout`...
