### ISSUE TITLE
DataGrid is not resizing properly inside DashboardLayout

### ISSUE THREAD

**Issue by Petar-Dimitrov-AXA** [mui/toolpad#4331]
### Steps to reproduce

When using DataGridPro within DashboardLayout, the table does not resize properly when the menu is expanded.

Here are the steps to reproduce the issue:

 1. Use the DataGridPro component with sufficient horizontal data and integrate it into a page with routing and navigation using
    React and toolpad.
 2. Initially, everything renders correctly.
 3. Collapse the menu and then expand it, at which point the DataGrid table does not resize properly.

To resolve this issue, you can add **overflow: hidden** to the 4th DOM element, which, in my case, is a div with the classname
**MuiBox-root** and is a child of the AppProvider root element.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: DataGridPro DashboardLayout

**Comment by Janpot** [comment]
Could you provide a codesandbox for us to demonstrate the issue? It's the best way for us to strip all ambiguity from the reproduction.

**Comment by apedroferreira** [comment]
Even without a reproduction we can still try to reproduce it from the initial instructions at least.
(The issue had auto-closed so I reopened it)

**Comment by Petar-Dimitrov-AXA** [comment]
The issue seems to be still closed. I didn't hat time the last week. I also  am not able to make some sandbox example. That what I can do is to attach some screenshots from our system.

**Comment by Janpot** [comment]
We can't debug from a screenshot. What's preventing you from creating a codesandbox?

**Comment by Petar-Dimitrov-AXA** [comment]
Time

**Comment by christiancookbuzz** [comment]
I've worked around this issue by applying `overflow: hidden` to the `DashboardLayout` nested `Box` component (Which is referenced in the original issue):

```jsx
<DashboardLayout
    sx={{
        '& > .MuiBox-root': {
            overflow: 'hidden'
        }
    }}
>
```

**Comment by apedroferreira** [comment]
There was an issue with the horizontal overflow in the dashboard.
Maybe this fix in the next release will solve this issue too? https://github.com/mui/toolpad/pull/4414

**Comment by christiancookbuzz** [comment]
I can confirm updating to `@toolpad/core@0.10.0` containing #4414 solves the DataGrid resizing issue for me and the workaround is no longer needed.
