### ISSUE TITLE
useDialogs Make Payload a Node Rather than a String

### ISSUE THREAD

**Issue by aress31** [mui/toolpad#4336]
### Summary

The [dialog payload](https://mui.com/toolpad/core/react-use-dialogs/#with-dialog-payload) specifies that payload is expected to be of type `string`, which feels restrictive. For example, my use case involves passing a complex form as the payload. Expanding support to allow any type of payload would be highly beneficial.

### Motivation

Extending the usefulness of `useDialogs`.

**Search keywords**: payload useDialogs

**Comment by Janpot** [comment]
You should be able to pass anything as a payload. e.g. you can pass an object as we do [internally](https://github.com/mui/toolpad/blob/affb770c769ffab78eb312794f4978705a9e0eb4/packages/toolpad-core/src/useDialogs/useDialogs.tsx#L302) for the system dialogs. The docs just use a string as an example. Perhaps we need to clarify this in the documentation?

**Comment by aress31** [comment]
I can confirm that it's possible to pass any payload, but the `PropType` in the example was somewhat unclear. It might be beneficial to include a note in the documentation to clearly state that any payload type is acceptable for the component, and to update the `PropType` from `string` to `any`.
