### ISSUE TITLE
[docs] 404 on examples page https://github.com/mui/toolpad/tree/master/examples/core-auth-nextjs

### ISSUE THREAD

**Issue by alexsenseer** [mui/toolpad#4365]
### Steps to reproduce

https://github.com/mui/toolpad/tree/master/examples/core-auth-nextjs

![image](https://github.com/user-attachments/assets/1027b60b-ac72-475e-83ac-5a9cf1dbbc77)

### Current behavior

404 in the example section of toolpad next js

### Expected behavior

Example is present and correct for next js app router and etc

### Your environment

Not Relevant

**Search keywords**: example nextjs core auth

**Comment by Janpot** [comment]
Looks like it has moved to a subfolder https://github.com/mui/toolpad/tree/master/examples/core/auth-nextjs
Are you interested in contributing a fix?

**Comment by bharatkashyap** [comment]
This was changed as part of https://github.com/mui/toolpad/pull/4301 - perhaps we can release a version of the docs to make it update?

**Comment by bharatkashyap** [comment]
Resolved with the latest docs release! Thanks for reporting
