### ISSUE TITLE
Default Sidebar Collapsed does not appear to work

### ISSUE THREAD

**Issue by adamsiwiec1** [mui/toolpad#4378]
### Steps to reproduce

Link to live example: (required)
![image](https://github.com/user-attachments/assets/df169c75-b4c1-418a-aa40-282f46b0ae9a)
https://mui.com/toolpad/core/api/dashboard-layout/#dashboard-layout-prop-defaultSidebarCollapsed

Steps:
1. Set defaultSidebarCollapsed to true. 
2. Or try the other properties.
3. Refresh your app and sidebar will remain open on refresh.

### Current behavior

The siderbar repons on refresh. 

### Expected behavior

I would like the sidebar to stay closed on page refreshed if the user had it closed previously, by using useLocalStorageState.

### Context

I would like the sidebar state to remain consistent across refreshes. I have tried all the available props and have read the source.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Sidebar opens on refresh Dashboard Layout AppProvider

**Comment by prakhargupta1** [comment]
I can't replicate it. Please share a codesandbox to help us debug it.

**Comment by apedroferreira** [comment]
Hey, we already have an issue for this at https://github.com/mui/toolpad/issues/4263
@prakhargupta1 I guess we can add it to a milestone soon since it's not the first time it's requested?

**Comment by apedroferreira** [comment]
Duplicate, will address this, thanks for reporting it!

**Comment by adamsiwiec1** [comment]
Thank you for addressing it! I see someone picked it up not too long ago
