### ISSUE TITLE
Export ThemeSwitcher component

### ISSUE THREAD

**Issue by SamuelLeapifai** [mui/toolpad#4379]
### Summary

Hi,
you already have the ThemeSwitcher component implemented (it's used in the DashboardLayout). Would you mind exporting it similarly to how you do Account? This would be very useful for using in other places.

This would also fix this #4328 . In my case, I have implemented my own theme switcher for login page but then my switcher persists a different value then yours and I would like to sync them (otherwise one can store "light" and the other "dark"). Currently I'm unable to sync them (as far as I know).

Should be a low-hanging fruit.

Thanks.

**Search keywords**: ThemeSwitcher, DashboardLayout

**Comment by apedroferreira** [comment]
Hey, it was just added in https://github.com/mui/toolpad/pull/4340, so it should be released very soon! (possibly tomorrow)

For now, it will be possible to import `ThemeSwitcher` as a named import from `'@toolpad/core/DashboardLayout` as shown in https://deploy-preview-4340--mui-toolpad-docs.netlify.app/toolpad/core/react-dashboard-layout/#slots.
