### ISSUE TITLE
Responsive bug with MUI component

### ISSUE THREAD

**Issue by ydainna** [mui/toolpad#4387]
### Steps to reproduce

Link to live example: (required)

Steps:
1.install MUI and toolpad in vite
2.use exemple vitejs integration 
3.add component table in your page for exemple
![image](https://github.com/user-attachments/assets/c0fbf898-d6d1-46df-9d7e-8cc1319f6f4d)

### Current behavior

My MUI components don't resize when I change the window size (desktop, tablet, mobile) when toolpad is installed.

### Expected behavior

MUI components must follow breakpoint size

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

  System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 20.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Chromium (129.0.2792.89)
  npmPackages:
    typescript: ^5.6.3 => 5.6.3 

**Search keywords**: MUI responsive bug

**Comment by bharatkashyap** [comment]
Hi! Can you create a minimal reproduction for us to be able to replicate this? A codesandbox link would work. I can't seem to reproduce 

https://github.com/user-attachments/assets/c9469727-2bb5-44e6-867f-75c2eef69fce

**Comment by ydainna** [comment]
ok i created a stackblitz test with vitejs

https://stackblitz.com/edit/vitejs-vite-mkfvgf?file=src%2Fmain.tsx

**Comment by bharatkashyap** [comment]
> ok i created a stackblitz test with vitejs
> 
> https://stackblitz.com/edit/vitejs-vite-mkfvgf?file=src%2Fmain.tsx

If I understand correctly, the issue is about the DataGrid scrolling? We're tracking that here as well https://github.com/mui/toolpad/issues/4407 and the fix here https://github.com/mui/toolpad/pull/4414

Here's a Stackblitz running with the corrected version https://stackblitz.com/edit/vitejs-vite-vk9u7p

**Comment by ydainna** [comment]
Oh ok ! thank
