### ISSUE TITLE
[example][pageContainer] Unable to scroll a Datagrid

### ISSUE THREAD

**Issue by prakhargupta1** [mui/toolpad#4407]
### Steps to reproduce

Steps:
1. Open the custom-themed example from: https://mui.com/toolpad/core/introduction/examples/ in codesandbox. (Stackblitz doesn't work)
2. In a smaller window, you'll notice that the datagrid doesn't scroll (as shown in the video)
3. It scrolls in https://mui.com/material-ui/getting-started/templates/dashboard/

https://github.com/user-attachments/assets/56cfd0cf-f188-4a1e-a70b-6bef163f85e5

**Search keywords**: datagrid

**Comment by alexwork1611** [comment]
Guys, this is a priority, in my opinion. I have the same problem.
