### ISSUE TITLE
Security Vulnerabilities in @toolpad/core

### ISSUE THREAD

**Issue by Petar-Dimitrov-AXA** [mui/toolpad#4478]
At this moment there 6 high severity vulnerabilities in @toolpad/core package. Is there any plan to fix those?

Here is the output of npm audit:

![image](https://github.com/user-attachments/assets/f5f473ef-f85d-4d74-8725-b2f8fabba2e4)

**Search keywords**:

**Comment by Janpot** [comment]
upstream issue https://github.com/vercel/title/issues/85. looks like it's fixed in there latest version.

**Comment by Janpot** [comment]
yes it will be part of next version. Just to note that the offending `cross-spawn` dependency is not being called. There is no real vulnerability here other than on paper.

**Comment by Petar-Dimitrov-AXA** [comment]
Ok, thanks a lot!

**Comment by Janpot** [comment]
we can leave this open for tracking purposes

**Comment by rolandjitsu** [comment]
@Janpot would it make sense to relax the dependencies so that patches are picked up on? E.g. in https://github.com/mui/toolpad/blob/b9315b686f72d53c9c97ec8d56db470725acf77b/packages/toolpad-utils/package.json#L64

one could use:
```
"title": "~4.0.1",
```

**Comment by Janpot** [comment]
yes, I wouldn't mind to even widen it to `^4.0.1`. are you interested in opening a PR for this?
