### ISSUE TITLE
[studio] Sign in button shows up on the tools-public app

### ISSUE THREAD

**Issue by prakhargupta1** [mui/toolpad#4479]
### Summary

We recently upgraded @toolpad/studio in [tools-public](https://tools-public.mui.com/prod/pages/OverviewPage) and now it uses the dashbaord layout component from toolpad core.

Problem: It shows a Sign in button in the app bar, but it's a public app that needs no authentication. So we need to remove it.

**Search keywords**: tools-public

**Comment by apedroferreira** [comment]
Should be fixed if we update to the latest version of `@toolpad/studio` I think... I've fixed it recently.

**Comment by prakhargupta1** [comment]
> Should be fixed if we update to the latest version of @toolpad/studio I think... I've fixed it recently.

Yes, it works in v0.10.0. Thanks.
PR: https://github.com/mui/mui-public/pull/250
