### ISSUE TITLE
The Mui X Data Grid does not resize correctly within the Toolpad core dashboard layout

### ISSUE THREAD

**Issue by OrwaPog** [mui/toolpad#4542]
### Steps to reproduce

Steps:
1. Setup toolpad core dashboard layout
2.create a random data grid and put it inside the layout
3.closing and opening the drawer should reproduce the issue

### Current behavior

https://github.com/user-attachments/assets/1f38ca7d-45fa-45ad-9db8-307abd33dc17

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Mui X data grid toolpad core

**Comment by bharatkashyap** [comment]
I can't seem to replicate it here: https://codesandbox.io/p/sandbox/nostalgic-flower-p7ztkz?file=%2Fsrc%2FDemo.tsx%3A47%2C25

Feel free to make edits to this sandbox to create a minimal reproduction of the issue 👍🏻
