### ISSUE TITLE
Unable to connect to an API

### ISSUE THREAD

**Issue by prakhargupta1** [mui/toolpad#527]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

From app page when trying to connect an API, Toolpad is showing this error: Connection "cl44165a200093f6eokrrz2ph" is not configured"

App: https://master--toolpad.mui.com/_toolpad/app/cl440iy0g00129yofn7vnhpgd/editor/pages/cl440iy3r00029yof6q2td60w

@joserodolfofreitas

**Comment by joserodolfofreitas** [comment]
My [second sandbox](https://master--toolpad.mui.com/_toolpad/app/cl442q35m18769yofm9khvcdo/editor/pages/cl442q35u00089yof09n8g29h) has the same problem
