### ISSUE TITLE
Can't delete an app

### ISSUE THREAD

**Issue by MonstraG** [mui/toolpad#573]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

![1](https://user-images.githubusercontent.com/17963791/174496983-c6702878-b0f3-4875-a82a-eadbece3fa51.gif)

### Expected behavior 🤔

It actually deletes.

### Steps to reproduce 🕹

Steps:

1. Create app
2. Go back to list (grid?) of apps
3. Try to delete it.

**Comment by MonstraG** [comment]
I don't think I need to create another issue for renaming that doesn't work and deploying that loads for a while but eventually sends to 404.

**Comment by bharatkashyap** [comment]
I can't seem to be able to replicate this @MonstraG:

https://user-images.githubusercontent.com/19550456/174504427-00e139a9-d985-4247-aa3b-e966c8d155e9.mov

Could you attach some additional information? Perhaps a screenshot from the browser console?

**Comment by MonstraG** [comment]
![2](https://user-images.githubusercontent.com/17963791/174529478-fe511730-6ca2-4dc0-b76b-22d8f5cd7050.gif)

**Comment by MonstraG** [comment]
This happens because it navigates to `?` because `Delete` is a `type="submit"` button inside of a `form`.

Changing it to `type="button"` fixes the problem.

**Comment by oliviertassinari** [comment]
I see the "regression" label was applied. Is there an opportunity to write some regression tests for them?
